import { KpiGroup } from '../src/models';

export const kpiGroupList: KpiGroup[] = [
  {
    id: Math.random().toString(36),
    category: 'Exklusive Kpis',
    kpis: [
      {
        id: Math.random().toString(36),
        label: 'Marketvalue',
        value: 5720000,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Rental Income',
        value: 204840,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Vacancy abs.',
        value: 44040,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Vacancy %',
        value: 5720000,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Gross Return (Target)',
        value: 0.036,
        format: 'percent',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Gross Return (actual)',
        value: 0.028,
        format: 'percent',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: '-',
        value: 0,
        format: '',
        trend: 0,
      },
    ],
  },
  {
    id: Math.random().toString(36),
    category: 'Exklusive Kpis',
    kpis: [
      {
        id: Math.random().toString(36),
        label: 'Marketvalue',
        value: 5720000,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Rental Income',
        value: 204840,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Vacancy abs.',
        value: 44040,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Vacancy %',
        value: 5720000,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Gross Return (Target)',
        value: 0.036,
        format: 'percent',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Gross Return (actual)',
        value: 0.028,
        format: 'percent',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: '-',
        value: 0,
        format: '',
        trend: 0,
      },
    ],
  },
  {
    id: Math.random().toString(36),
    category: 'Exklusive Kpis',
    kpis: [
      {
        id: Math.random().toString(36),
        label: 'Marketvalue',
        value: 5720000,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Rental Income',
        value: 204840,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Vacancy abs.',
        value: 44040,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Vacancy %',
        value: 5720000,
        format: 'number',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Gross Return (Target)',
        value: 0.036,
        format: 'percent',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: 'Gross Return (actual)',
        value: 0.028,
        format: 'percent',
        trend: 1,
      },
      {
        id: Math.random().toString(36),
        label: '-',
        value: 0,
        format: '',
        trend: 0,
      },
    ],
  },
];
